name: Doxygen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Doxygen documentation
      run: doxygen Doxyfile

    - name: Deploy doxygen
          uses: JamesIves/github-pages-deploy-action@v4
          with:
              ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              BRANCH: gh-pages # The branch the action should deploy to.
              FOLDER: docs # The folder the action should deploy.
              TARGET_FOLDER: main
